import axios from "axios";
import FileUploader from "../utils/fileUploader";
import { getUID } from "../utils/helpers";

/**
 * Simple upload helper for host apps.
 * Uploads a file and resolves with the raw FileUploader success payload.
 *
 * @param {object} args
 * @param {File} args.file File object to upload.
 * @param {string} [args.fileContext='runtime'] Backend file context.
 * @param {string} [args.mediaName] Optional media name; autogenerated when omitted.
 * @param {string} [args.userId] Optional override; defaults to window.sdkConfig.userId.
 * @param {string} [args.userAccessToken] Optional override; defaults to window.sdkConfig.accessToken.
 * @param {string} [args.boardId] Optional board id for scoped uploads.
 * @param {string} [args.pageId] Optional page id for scoped uploads.
 * @param {string} [args.resourceId] Optional integration resource id.
 * @param {string} [args.resourceType] Optional integration resource type.
 * @param {string} [args.rowId] Optional integration row id.
 * @param {string} [args.tableId] Optional integration table id.
 * @param {string} [args.scope] Optional integration scope.
 * @param {(progress: number|object) => void} [args.onProgress] Upload progress callback.
 * @returns {Promise<object>} Raw FileUploader success payload.
 */
const UploadFile = ({
  file,
  fileContext = "runtime",
  mediaName,
  userId,
  userAccessToken,
  boardId,
  pageId,
  resourceId,
  resourceType,
  rowId,
  tableId,
  scope,
  onProgress,
} = {}) => {
  if (!file) {
    return Promise.resolve({
      status: "failed",
      error: { message: "file is required" },
      data: null,
    });
  }

  const sdkConfig = window?.sdkConfig || {};
  const resolvedUserId = userId || sdkConfig.userId;
  const resolvedUserAccessToken = userAccessToken || sdkConfig.accessToken;

  if (!resolvedUserId || !resolvedUserAccessToken) {
    return Promise.resolve({
      status: "failed",
      error: { message: "SDK not initialized. userId and accessToken are required" },
      data: null,
    });
  }

  const source = axios.CancelToken.source();
  const resolvedMediaName = mediaName || getUID(6);

  return new Promise((resolve) => {
    const uploader = new FileUploader({
      file,
      userInfoId: resolvedUserId,
      fileContext,
      userAccessToken: resolvedUserAccessToken,
      mediaName: resolvedMediaName,
      boardId,
      pageId,
      resourceId,
      resourceType,
      rowId,
      tableId,
      scope,
      source,
    });

    uploader.start(
      (progressResp) => {
        if (typeof onProgress === "function") {
          onProgress(progressResp);
        }
      },
      (data) => {
        resolve({
          status: "success",
          error: null,
          data,
          cancelSource: source,
        });
      },
      (msg, errorData) => {
        resolve({
          status: "failed",
          error: {
            message: msg || "FILE_UPLOAD_ERROR",
            data: errorData || null,
          },
          data: null,
          cancelSource: source,
        });
      }
    );
  });
};

export default UploadFile;
